export default [
  {
    id: 1,
    lawyerName: 'Anil Thapa',
    fieldOfExpertise: 'Immigration',
    timeAvailable: [
      '9:00 AM',
      '10:00 AM',
      '11:00 AM',
      '1:00 PM',
      '2:00 PM',
      '3:00 PM',
    ],
  },
  {
    id: 2,
    lawyerName: 'Jennifer Attsion',
    fieldOfExpertise: 'Marriage',
    timeAvailable: [
      '9:00 AM',
      '10:00 AM',
      '11:00 AM',
      '1:00 PM',
      '2:00 PM',
      '3:00 PM',
    ],
  },
  {
    id: 3,
    lawyerName: 'Jessica Snowsen',
    fieldOfExpertise: 'Real Estate',
    timeAvailable: [
      '9:00 AM',
      '10:00 AM',
      '11:00 AM',
      '1:00 PM',
      '2:00 PM',
      '3:00 PM',
    ],
  },
  {
    id: 4,
    lawyerName: 'Jacob Henderson',
    fieldOfExpertise: 'Real Estate',
    timeAvailable: [
      '9:00 AM',
      '10:00 AM',
      '11:00 AM',
      '1:00 PM',
      '2:00 PM',
      '3:00 PM',
    ],
  },
  {
    id: 5,
    lawyerName: 'Sushant Kuikel',
    fieldOfExpertise: 'Immigration',
    timeAvailable: [
      '9:00 AM',
      '10:00 AM',
      '11:00 AM',
      '1:00 PM',
      '2:00 PM',
      '3:00 PM',
    ],
  },
  {
    id: 6,
    lawyerName: 'John Miller',
    fieldOfExpertise: 'Immigration',
    timeAvailable: [
      '9:00 AM',
      '10:00 AM',
      '11:00 AM',
      '1:00 PM',
      '2:00 PM',
      '3:00 PM',
    ],
  },
  {
    id: 7,
    lawyerName: 'Puja Thapa',
    fieldOfExpertise: 'Marriage',
    timeAvailable: [
      '9:00 AM',
      '10:00 AM',
      '11:00 AM',
      '1:00 PM',
      '2:00 PM',
      '3:00 PM',
    ],
  },
  {
    id: 8,
    lawyerName: 'Saif Ansari',
    fieldOfExpertise: 'Marriage',
    timeAvailable: [
      '9:00 AM',
      '10:00 AM',
      '11:00 AM',
      '1:00 PM',
      '2:00 PM',
      '3:00 PM',
    ],
  },
];
